name: build-openwrt-imagebuilder

on: 
  push:
    tags: 
      - 'v*'
  workflow_dispatch:
  # watch:
  #   types: started

env:
  VERSION: 21.02.2
  TZ: Asia/Shanghai

jobs:
  build_openwrt:
    name: Build OpenWrt and Release
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: checkout
      uses: actions/checkout@master

    - name: cleanup
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        [[ -f /swapfile ]] && sudo swapoff /swapfile
        [[ -f /swapfile ]] && sudo rm -rf /swapfile
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python qemu-utils
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: prepare
      run: |
        wget https://download3.vmware.com/software/WKST-1623-LX-New/VMware-Workstation-Full-16.2.3-19376536.x86_64.bundle
        chmod +x VMware-Workstation-Full-16.2.3-19376536.x86_64.bundle
        sudo ./VMware-Workstation-Full-16.2.3-19376536.x86_64.bundle
        wget https://archive.openwrt.org/releases/${VERSION}/targets/x86/64/openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64.tar.xz
        tar -xf openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64.tar.xz
        cd openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64
        sed -i '/^CONFIG_TARGET_ROOTFS_TARGZ/d' .config
        sed -i '/^CONFIG_GRUB_EFI_IMAGES/d' .config 
        sed -i '/^CONFIG_TARGET_ROOTFS_SQUASHFS/d' .config
        sed -i '/^CONFIG_GRUB_TIMEOUT/d' .config
        sed -i '/^CONFIG_TARGET_IMAGES_GZIP/d' .config
        sed -i '/^CONFIG_TARGET_KERNEL_PARTSIZE/d' .config
        sed -i '/^CONFIG_TARGET_ROOTFS_PARTSIZE/d' .config

    - name: make
      run: |
        cd openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64
        make image PROFILE=generic PACKAGES="-bnx2-firmware -dnsmasq busybox dnsmasq-full luci luci-compat luci-i18n-base-zh-cn kmod-e100 kmod-e1000 kmod-vmxnet3 kmod-wireguard wireguard-tools luci-app-wireguard vpn-policy-routing luci-i18n-wireguard-zh-cn iptables iptables-mod-conntrack-extra iptables-mod-extra iptables-mod-tproxy ipset open-vm-tools" CONFIG_GRUB_TIMEOUT="0" CONFIG_VDI_IMAGES=y CONFIG_VMDK_IMAGES=y CONFIG_TARGET_KERNEL_PARTSIZE=128 CONFIG_TARGET_ROOTFS_PARTSIZE=2048

    - name: package
      run: |
        echo $PWD
        cd /home/runner/work/openwrt-package-ci/openwrt-package-ci
        tree openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64/bin/targets/x86/64
        mkdir images
        # cp openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64/bin/targets/x86/64/* images
        cp openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64/bin/targets/x86/64/openwrt-${VERSION}-x86-64-generic-ext4-combined.vmdk images/
        cp images/openwrt-${VERSION}-x86-64-generic-ext4-combined.vmdk buildova/openwrt.vmdk
        ovftool buildova/openwrt.vmx images/openwrt-${VERSION}-x86-64.ova
        # qemu-img convert -O vmdk -o subformat=streamOptimized images/openwrt-${VERSION}-x86-64-generic-ext4-combined.img buildova/openwrt.vmdk
        cd buildova
        # sha256sum --tag openwrt* > openwrt.mf
        cd ..
        # tar -C buildova --owner=root --group=root -cf images/openwrt-${VERSION}-x86-64.ova openwrt.ovf openwrt.vmdk openwrt.mf
        tree images
        # tar -zcvf openwrt-${VERSION}-x86-64.Linux-x86_64.tar.gz images/*
        ls -al

    - name: test
      run: |
        sudo apt install virtualbox -y
        # echo "-------------ovf dry-run-------------"
        # VBoxManage import buildova/openwrt.ovf --dry-run
        echo "-------------ova dry-run-------------"
        VBoxManage import images/openwrt-${VERSION}-x86-64.ova --dry-run
        
    - name: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: images/*
        prerelease: ${{ contains(github.ref, '-') }}


