name: build-openwrt-18.06-firmware

on: 
  push:
    tags: 
      - 'v0.11'

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  CONFIG_FILE: config.x64
  CONFIG_FILE_PKG: config.pkg
  FREE_UP_DISK: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
  
      - name: Initialization
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff /swapfile
          sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php
          sudo docker rmi `docker images -q`
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
  
      - name: Clean
        if: env.FREE_UP_DISK == 'true'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet
          docker rmi `docker images -q`
          sudo -E apt-get -q purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
  
      - name: make image
        working-directory: /workdir
        run: |
          git clone $REPO_URL -b openwrt-18.06 openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          git clone https://github.com/kenzok8/openwrt-packages package/openwrt-packages
          git clone https://github.com/kenzok8/small package/small       
          rm -f .config
          [ -e $CONFIG_FILE_PKG ] && mv $CONFIG_FILE_PKG .config
          make defconfig
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          make download -j8
          make -j$(nproc) || make -j1 V=s
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "::set-env name=DEVICE_NAME::_$(cat DEVICE_NAME)"
          echo "::set-env name=FILE_DATE::_$(date +"%Y%m%d%H%M")"
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
  
      - name: Upload bin directory
        uses: actions/upload-artifact@master
        if: steps.compile.outputs.status == 'success'
        with:
          name: OpenWrt-${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: openwrt/bin