name: build-openwrt-imagebuilder

# on: 
#   push:
#     tags: 
#       - 'v0.3'
on:
  workflow_dispatch:
  # watch:
  #   types: started

env:
  VERSION: 21.02.2
  TZ: Asia/Shanghai

jobs:
  build_openwrt:
    name: Build OpenWrt and Release
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: checkout
      uses: actions/checkout@master

    - name: cleanup
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        [[ -f /swapfile ]] && sudo swapoff /swapfile
        [[ -f /swapfile ]] && sudo rm -rf /swapfile
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python qemu-utils
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: prepare
      run: |
        wget https://archive.openwrt.org/releases/${VERSION}/targets/x86/64/openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64.tar.xz
        tar -xf openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64.tar.xz
        cd openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64
        sed -i '/^CONFIG_TARGET_ROOTFS_TARGZ/d' .config
        sed -i '/^CONFIG_GRUB_EFI_IMAGES/d' .config 
        sed -i '/^CONFIG_TARGET_ROOTFS_SQUASHFS/d' .config
        sed -i '/^CONFIG_GRUB_TIMEOUT/d' .config
        sed -i '/^CONFIG_TARGET_IMAGES_GZIP/d' .config
        sed -i '/^CONFIG_TARGET_KERNEL_PARTSIZE/d' .config
        sed -i '/^CONFIG_TARGET_ROOTFS_PARTSIZE/d' .config

    - name: make
      run: |
        cd openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64
        make image PROFILE=generic PACKAGES="-bnx2-firmware -dnsmasq busybox dnsmasq-full luci luci-compat luci-i18n-base-zh-cn kmod-e100 kmod-e1000 kmod-vmxnet3 kmod-wireguard wireguard-tools luci-app-wireguard vpn-policy-routing luci-i18n-wireguard-zh-cn iptables iptables-mod-conntrack-extra iptables-mod-extra iptables-mod-tproxy ipset open-vm-tools" \ 
        CONFIG_GRUB_TIMEOUT="0" CONFIG_VMDK_IMAGES=y CONFIG_TARGET_KERNEL_PARTSIZE=128 CONFIG_TARGET_ROOTFS_PARTSIZE=2048

    - name: test && package
      working-directory: /workdir
      run: |
        tree openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64/bin/targets/x86/64
        cd openwrt-imagebuilder-${VERSION}-x86-64.Linux-x86_64/bin/targets/x86/64
        qemu-img info *.img
        qemu-img info *.vmdk
        tar -zcf /workdir/openwrt-${VERSION}-x86-64.Linux-x86_64.tar.gz *
        ls -al /workdir
        
#     - name: upload artifact
#       uses: actions/upload-artifact@master
#       with:
#         name: OpenWrt-${{ env.VERSION }}
#         path: ./openwrt-${VERSION}-x86-64.Linux-x86_64.tar.gz


