name: build-openwrt-imagebuilder

on: 
  push:
    tags: 
      - 'v0.3'
  # watch:
  #   types: started

env:
  VERSION: 19.07.0
  TZ: Asia/Shanghai

jobs:
  build_openwrt:
    name: Build OpenWrt 19.07 and Release
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: checkout
      uses: actions/checkout@master

    - name: cleanup
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: openwrt-imagebuilder
      run: |
        wget https://archive.openwrt.org/releases/$VERSION/targets/x86/64/openwrt-imagebuilder-$VERSION-x86-64.Linux-x86_64.tar.xz
        tar -xf openwrt-imagebuilder-*-x86-64.Linux-x86_64.tar.xz
        cd openwrt-imagebuilder-*
        sed -i 's/192.168.1.1/172.16.32.8/g' .config

    - name: make
      run: |
        make image PROFILE=Generic PACKAGES="-bnx2-firmware -dnsmasq dnsmasq-full luci luci-i18n-base-zh-cn kmod-e100 kmod-e1000 kmod-vmxnet3 kmod-wireguard" \ 
        CONFIG_TARGET_KERNEL_PARTSIZE=256 CONFIG_TARGET_ROOTFS_PARTSIZE=1024

    - name: tar
      working-directory: /workdir
      run: |
        cd ./openwrt-imagebuilder-*/bin/targets/x86/64 && tar -zcf ./openwrt-imagebuilder-*/openwrt.tar.gz *

    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt-${{ env.VERSION }}
        path: ./openwrt-imagebuilder-*/openwrt.tar.gz


