name: test

on: 
  push:
    tags: 
      - 'v0.3.3'
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: checkout
      uses: actions/checkout@master

    - name: ready
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        cd /workdir
        echo "hello world" > test-$(date +%Y%m%d).txt
   
    - name: scp
      run: |
        cat ${{ secrets.SERVER_SSH_KEY }} > ./sshkey
        chmod 0400 ./sshkey
        scp /workdir/test-*.txt -o StrictHostKeyChecking=no -i ./sshkey ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}