name: test

on: 
  push:
    tags: 
      - 'v0.3.1'
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: checkout
      uses: actions/checkout@master

    - name: ready
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        cd /workdir
        echo "hello world" > test-$(date +%Y%m%d).txt

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.KEY }}
        port: 22
        source: "/workdir/test-*.txt"
        target: ${{ secrets.REMOTE_TARGET }}