name: test

on: 
  push:
    tags: 
      - 'v0.3.4'
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: checkout
      uses: actions/checkout@master

    - name: ready
      run: |
        sudo apt install -y openssh*
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        cd /workdir
        echo "hello world" > test-$(date +%Y%m%d).txt
   
    - name: scp
      run: |
        eval "$(ssh-agent -s)"
        cat ${{ secrets.SERVER_SSH_KEY }} > sshkey
        cat sshkey && chmod 0600 sshkey
        ssh-add -k sshkey
        echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
        scp /workdir/test-*.txt ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}