name: test

on: 
  push:
    tags: 
      - 'v0.3.1'
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: checkout
      uses: actions/checkout@master

    - name: ready
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        cd /workdir
        echo "hello world" > test-$(date +%Y%m%d).txt

    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/workdir/test-*.txt"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}